// Demo catalog for the MFH Hair storefront. Prices/specifications are samples;
// the owner must confirm stock, exact product variants, and pricing before sales.
// Product photos link to third-party listings for demonstration and are not MFH
// Hair-owned assets. Replace them with supplier-approved or owner-owned photos.
export const products = [
  { id: "p1", name: "The Everyday Kinky Pony", type: "Ponytails", material: "Drawstring ponytail · sample listing", price: 12500, badge: "EVERYDAY EDIT", photo: "https://www.mshair.com/cdn/shop/products/ms-remy-human-hair-kinky-curly-drawstring-ponytail-model-show_a8f4d0f0-0949-40cc-bece-0364ffe6bbc5_720x.jpg?v=1648258199", photoSource: "Modern Show Hair", photoLink: "https://www.mshair.com/products/modern-show-kinky-curly-drawstring-ponytail-brazilian-human-hair-clip-in-extensions-natural-afro-curly-hairstyle", short: "A softly textured ponytail for an easy style." },
  { id: "p2", name: "Sleek Wrap Ponytail", type: "Ponytails", material: "Wrap ponytail · sample listing", price: 14500, badge: "SLEEK FINISH", photo: "https://www.mshair.com/cdn/shop/products/ms-remy-human-hair-wrap-around-ponytail-yaki-straight-human-hair-clip-in-velcro-ponytail-model-show_1400x.jpg?v=1652857715", photoSource: "Modern Show Hair", photoLink: "https://www.mshair.com/products/modern-show-afro-kinky-curly-yaki-straight-ponytail-human-hair-drawstring-brazilian-hair-extensions-pony-tail-for-women-clip-in-hair", short: "A smooth, polished ponytail look." },
  { id: "p3", name: "Kinky Curly Ponytail", type: "Ponytails", material: "Textured ponytail · sample listing", price: 123500, badge: "TEXTURED", photo: "https://image.made-in-china.com/202f0j00koEztYhrqlcK/Kbeth-Kinky-Curly-Ponytail-for-Black-Girls-2021-Fashion-Cool-Easy-to-Install-New-Style-18-Inch-Human-Hair-Custom-Accept-Ready-to-Ship-Ponytails-China-Wholesale.webp", photoSource: "Made-in-China", photoLink: "https://sa.made-in-china.com/co_kbethhair/product_Kbeth-Kinky-Curly-Ponytail-for-Black-Girls-2021-Fashion-Cool-Easy-to-Install-New-Style-18-Inch-Human-Hair-Custom-Accept-Ready-to-Ship-Ponytails-China-Wholesale_uougsngiig.html", short: "A fuller textured look with natural movement." },
  { id: "p4", name: "Natural Black Bundle Set", type: "Bundles", material: "Straight bundles · sample listing", price: 145000, badge: "BUNDLE SET", photo: "https://media.takealot.com/covers_images/cf4fd1b04d434a75aa432b34059669b7/s-zoom.file", photoSource: "Takealot", photoLink: "https://www.takealot.com/hair-extensions-8-18-full-shine-human-hair-4-bundles-200g-golden/PLID97460262", short: "A classic bundle set for your next style." },
  { id: "p5", name: "Afro Kinky Curl Lace Wig", type: "Wigs", material: "Kinky curl wig · sample listing", price: 155000, badge: "FULL LOOK", photo: "https://www.mshair.com/cdn/shop/files/kinkyCurlywig_720x.jpg?v=1698455739", photoSource: "Modern Show Hair", photoLink: "https://www.mshair.com/products/human-hair-kinky-curly-lace-front-wigs-for-black-women", short: "A ready-to-style look with soft volume." },
  { id: "p6", name: "Soft Curl Clip-ins", type: "Extensions", material: "Curly clip-ins · sample listing", price: 18500, badge: "QUICK CHANGE", photo: "https://pahairextensions.com/cdn/shop/files/2-Curly-Clip-In.jpg?v=1748824880&width=1000", photoSource: "PA Hair Extensions", photoLink: "https://pahairextensions.com/en-gb/collections/clip-in-hair-extensions-curly-hair", short: "Add curl and fullness in a few minutes." },
  { id: "p7", name: "Chocolate Straight Bundles", type: "Bundles", material: "Straight bundles · sample listing", price: 98000, badge: "RICH TONE", photo: "https://cheetahbeauty.com/cdn/shop/files/4ChocolateBrownStraightBundlesCheetahBeauty100_VirginHumanHairExtension_3.jpg?v=1734591158&width=1080", photoSource: "CheetahBeauty", photoLink: "https://cheetahbeauty.com/products/4-chocolate-brown-straight-bundles-cheetahbeauty-100-virgin-human-hair-extension", short: "A deep brown shade with a sleek finish." },
  { id: "p8", name: "Natural Black Weft Set", type: "Bundles", material: "Straight wefts · sample listing", price: 112000, badge: "CLASSIC", photo: "https://www.hairlaya.us/cdn/shop/files/Hybridweft-_24wefts-Head_940x940px_df6cbbb6-057d-4fae-bef1-6afaff600b46.png?v=1742797668&width=940", photoSource: "Hairlaya", photoLink: "https://www.hairlaya.us/products/1b-natural-black-genius-hybrid-weft-full-cuticle-human-hair-extensions-double-drawn-4-wefts-2", short: "A classic straight style for versatile installs." },
  { id: "p9", name: "Curly Lace Frontal Wig", type: "Wigs", material: "Curly lace wig · sample listing", price: 168000, badge: "CURL MOMENT", photo: "https://oqhair.com/cdn/shop/files/7_9c8ddec7-857f-4e02-adf6-5fd63c7dcfa1.jpg?v=1775813349&width=720", photoSource: "OQ Hair", photoLink: "https://oqhair.com/products/kinky-curly-lace-frontal-wig", short: "Defined curls with a natural-looking part." },
  { id: "p10", name: "Glueless Curly Bob", type: "Wigs", material: "Curly bob wig · sample listing", price: 142000, badge: "EASY WEAR", photo: "https://www.tunefulhair.com/cdn/shop/files/NATURAL_2.jpg?v=1772777999&width=950", photoSource: "Tuneful Hair", photoLink: "https://www.tunefulhair.com/products/super-deal-summer-style-curly-6x5-wear-go-glueless-lace-human-hair-wigs", short: "A cropped curly look for a fresh change." },
  { id: "p11", name: "Curly Volume Clip-ins", type: "Extensions", material: "Curly clip-in set · sample listing", price: 26500, badge: "ADD VOLUME", photo: "https://media.ulta.com/i/ulta/77003731_alt01?fmt=auto&h=600&w=600", photoSource: "Ulta Beauty", photoLink: "https://www.ulta.com/p/sasha-curl-deep-curly-human-hair-clip-ins-extensions-mkt77002258?sku=77003731", short: "Clip-in pieces to build a fuller curl shape." },
  { id: "p12", name: "Pre-stretched Braid Pack", type: "Braiding hair", material: "Braiding hair · sample listing", price: 8500, badge: "BRAID EDIT", photo: "https://www.cosmeticconnection.co.za/cdn/shop/files/14209.jpg?v=1691582359&width=600", photoSource: "Cosmetic Connection", photoLink: "https://www.cosmeticconnection.co.za/collections/vendors?q=Darling", short: "A ready-to-style braid pack for protective looks." },
];

export const productCategories = ["All pieces", "Ponytails", "Wigs", "Bundles", "Extensions", "Braiding hair"];
